vich_uploader:
    db_driver: orm


    mappings:
        property_image:
            uri_prefix: /images/media
            upload_destination: '%kernel.project_dir%/public/images/media'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    # mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
